#
# Copy this to config.yml and change the values
#

image_url: "http://dev.iron.io/images/iron_pony.png"
aws:
    access_key: "YOUR ACCESS KEY"
    secret_key: "YOUR SECRET KEY"
    s3_bucket_name: "BUCKET NAME"

