require 'bundler'
require 'rake/testtask'
require 'tmpdir'

Dir.chdir(File.dirname(__FILE__) + '/..')

tmpdir = Dir.mktmpdir
File.open(tmpdir + '/Gemfile', 'w') do |f|
  f << File.read('Gemfile')
  f << File.read('test/Gemfile')
end
Dir.chdir tmpdir do
  Bundler.setup
end

Rake::TestTask.new do |t|
  examples_tests_dir = Dir.mktmpdir('iw_examples')

  FileUtils::cp_r(Dir.glob('examples/*'), examples_tests_dir)

  Dir.glob('examples/**/**.rb').each do |path|
    next unless path =~ %r|examples/(.*)/([^/]+)/\2.rb$|

    dir = $1
    name = $2

    test_path = examples_tests_dir + "/#{dir}/#{name}/test_example_#{name}.rb"

    File.open(test_path, 'w') do |out|
      out << "require 'helpers'\n"
      out << "class #{name.capitalize}Test < Test::Unit::TestCase\n"
      out << "def test_example\n"

      File.readlines(path).each do |line|
        line, assert_str = line.chomp.split /#>/
        out << line << "\n"

        if assert_str
          cond, desc = assert_str.split /--/
          out << "assert(" << cond << ", '" <<
            (desc or "").gsub(/'/, "\\\\'") << "')\n"
        end
      end

      out << "end\nend\n"
    end
  end

  t.libs << "lib" << "test" << examples_tests_dir
  files = FileList['test/**/test_**.rb',
                   examples_tests_dir + '/**/test_*.rb']
  $:.each{ |path| t.ruby_opts << "-I#{path}" }
  t.test_files = files.keep_if do |f|
    f =~ Regexp.new(ENV['TESTP'] || '') and
      not ( r = ENV['EXCLP'] and
            f =~ Regexp.new(r) )
  end

  t.verbose = true
end
